### ISSUE TITLE
Generate Config file if none exists

### ISSUE THREAD

**Issue by MrTechGadget** [MrTechGadget/aw-tag-script#6]
I will incorporate the same logic from https://github.com/MrTechGadget/aw-bulkdevices-script to generate the config file via prompts if it doesn't exist.

**Comment by subbzz** [comment]
Hi MrTechGadet, many thanks for your scripts, really good. Is there any way to grab all devices from all groups rather than collecting data group by group. I want to run a job on our servers to check all devices that are not seen over 20 days to be removed automatically every day. 

Thanks.
Siva

**Comment by MrTechGadget** [comment]
Siva, what you want to do is definitely possible, but the current status of these scripts is a somewhat interactive use. Sounds like you are really wanting the remove device functionality in the aw-bulkdevices-script to be able to be called via parameters. 

This is definitely something I want to support, please open an issue for this in that repo and I will see what I can do to get there.

**Comment by subbzz** [comment]
Many thanks. I just added a new issue to your queue.

Kind regards
Siva

**Comment by MrTechGadget** [comment]
Added Config file generation in commit 54fa36f
